### ISSUE TITLE
todo: sync site and docs in /docs main repo

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#40]
the http://moonlightde.github.io/mlde.d.moonlightde/ must be sync fro a complex branch repo to a more single (due staled) directory inside the repository 

currently github has the hability to convert markdown sintax into HTML5 so lets rock in simple things!

- [x] make a docs directory on each repo with proper docs of each one  982bc601
- [x] deletes the branchs of gh-pages and use the docs directory
- [x] migrate to the pages in docs in each project settings->ghpages
- [X] produce main page content with staled project status  982bc601

**Comment by mckaygerhard** [comment]
each isue will be locket until reorganization its done, then unlocket to receive others..

**Comment by mckaygerhard** [comment]
window manager minimal site : https://moonlightde.github.io/mlde.w.eggwm/

**Comment by mckaygerhard** [comment]
fine continuation of this work are now in #51
