### ISSUE TITLE
todo: sync and refresh the git init submodules

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#42]
the lxqt and qtxdg depends are set already as submodules in the main git repository
currently the depends submodules are set to:
* liblxqt@2d13fe1 too older, at 2014, we need some fixed until sep 2015
* libqtxdg@48e366e  too older, at 2014, we need some fixed until oct 2015
* microcpp services was forked and staled in own repository and library

- [x] remove and update the microcpp submodule to a depens event a thirthparty
- [x] try to determine what point commit must be tracket as depends
- [x] track and determine minimun commit start of each modules
- [x] fork repository in that point for each ones MoonLightDE/mlde.l.libmlde@d4cca89cf769a039f151cfd7f7176b7e68844929

Potencially track comit to start:
   - build deps: lxqt are lxde/liblxqt@534c7cd
   - build deps: qtxdg are lxde/libqtxdg@cbc22cc

**Comment by mckaygerhard** [comment]
trying again: 

1. lxde/libqtxdg@48e366e trying to up to lxde/libqtxdg@941cdd24774450c1cbabc5f985693584918e3a4e and start commits and patches from that as code base
2. lxde/liblxqt@2d13fe1 up and start commits and patches in lxde/liblxqt@079768e83768ce0fcb8092325b63d0ed7d3dae03 to avoid KF5 kde5 frameworks in moonlightde depends

**Comment by mckaygerhard** [comment]
taking in consideration errors of that tyle:

https://github.com/ola-ct/Qt-SESAM/issues/120

**Comment by mckaygerhard** [comment]
- qtzdg can be use 2.0.0
- liblxqt : forked MoonLightDE/mlde.l.liblxqt@d4cca89cf769a039f151cfd7f7176b7e68844929
