### ISSUE TITLE
todo: sync and fix the microcpp git submodule

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#43]
the main repository has a older and unfixed microcpp reference as submidule

- [ ] fix the reference to the moonlight microcpp fixed repository forked
- [ ] update the git submodule and set
- [ ] update documentation for develop and main branches

**Comment by mckaygerhard** [comment]
close with 142bd8acf8d840d7f601222acf1edf8d6c01d8fe

1. Delete the relevant section from the `.gitmodules` file
2. Delete the relevant section from `.git/config`
3. Run to commited and mark to delete `git add .gitmodules`
3. Run to fs deletion `git rm --cached thirdParty/CppMicroServices`
4. Now we have own staled lib, will be in depends `mkdir depends`
5. `git submodule add https://github.com/MoonLightDE/mlde.l.cppmicroservices depends/mlde.l.cppmicroservices`
