### ISSUE TITLE
todo: init the repo of the staled liblxqt as moonligh lib

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#48]
due #42  we need to update and set a staled liblxqt as a libmlde library

The liblxde: are between 0.7.0 and 0.9.0, but since Oct/31/2014 uses kde5 framework and then deletes the Xfigman X11 depends.. moonlightde panel depends and uses x11 code so depends on xfigman so the maximun commit point to staled are lxde/liblxq@fd3dee164136121520190f859b69948f77cdece0 but we need commits until lxde/liblxqt@079768e83768ce0fcb8092325b63d0ed7d3dae03 to make compatible with qt5 recent versions, so:

### objetives
1. start point are: https://github.com/lxde/liblxqt/commits/master?after=3c9ffefbdba89835bb0ccb197c98d7eb828d305d+209 at the 25 Oct 2014
2. we need updates until https://github.com/lxde/liblxqt/commits/master?after=3c9ffefbdba89835bb0ccb197c98d7eb828d305d+174 at the 7 Nov 2014
3. we need all the possible fixeds until  6 Apr 2015 at the c++11 suppot vs c++0x support to permit compile at wheeze and also jeesie
### tasks to do:
- [x] init and create the repository -> https://github.com/MoonLightDE/mlde.l.libmlde
- [x] parse and import code base from 0.8.0: MoonLightDE/mlde.l.libmlde@d4cca89cf769a039f151cfd7f7176b7e68844929
- [x] commit all the need changes made to able to build agains older or newer version qt5xdg
- [x] commit updates set patches for able to compile -> MoonLightDE/mlde.l.liblxqt@677cd66e2fa779debf6e6c20fcda28cd4e022a54

now new depends are, each module need document specific depends.. due the behaviour of the project each depends will be a separate library  : mlde.l.libmlde

**Comment by mckaygerhard** [comment]
repo created at https://github.com/MoonLightDE/mlde.l.liblxqt

**Comment by mckaygerhard** [comment]
parse codebase to 0.7.0 + pre 0.8.0 at MoonLightDE/mlde.l.liblxqt@d4cca89cf769a039f151cfd7f7176b7e68844929

**Comment by mckaygerhard** [comment]
able to compile now: MoonLightDE/mlde.l.liblxqt@677cd66e2fa779debf6e6c20fcda28cd4e022a54

**Comment by mckaygerhard** [comment]
leave it the patch lxde/liblxqt@4f07364e9bc2b3426b67c7d430210bb90097993e for later in a specific issue for the lib...

set of patches for cmake to pending: https://github.com/lxde/liblxqt/commits/master?before=3c9ffefbdba89835bb0ccb197c98d7eb828d305d+175 since 26 Jun 2015

**Comment by mckaygerhard** [comment]
last track comit now lib are able to use it at this point:

MoonLightDE/mlde.l.liblxqt@86695f4fb4a517a45cc95af6af877034fe322557
