### ISSUE TITLE
todo: refatoring libLXQT to libMLDE library

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#49]
The main its to conserver the main work of moonlightde.. 
1. if use the liblxqt up to date, many calls in moonlightde must be changed
2. if there is the case, its nonsense, so moonlightde will be a lxde copy-like implementation
3. that's will be in a lot of work
4. it's more easy to transform liblxde int libmlde and carry some patches
based on track lxde/liblxqt@f05ba5a to rename to libmlde

Let's take in consideration that **mayor changes in the liblxqt libraty are related to translations**, some about deprecation call of razorqt and systemd powermanagement implementation, **no mayor qt5 api changes are trak on the commits history**

- [ ] make a new branch of renaming task in mlde.l.liblxqt
- [ ] renaming any ocurrences of lxqt into mlde in the source code
- [ ] renamin library name and cmake calls tof lxqt to mlde
- [ ] make a new  branch of that implementation in moonlightde
- [ ] reimplements all the calls of liblxde to the newes reanmed libmlde
- [ ] merge the new branch renaming liblxde in master if works
- [ ] merge the new branch renamin moonlightde in master if works
- [ ] rename the moonlightde liblxqt repository to mlde.l.libmlde
- [ ] update the moonlightde submodule and finish the migration
