### ISSUE TITLE
todo: README and CONTRIB guidelines documentation

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.d.moonlightde#51]
Update the README's of all the staled repositoryes, and update the readme of the unstable branchs

- [ ] update README's of the main repository to point to README index in docs
     - [ ] updates and link in docs for mlde.d.moonlightde
     - [ ] updates and link in docs for mlde.l.cppmicroservices
     - [ ] updates and link in docs for mlde.l.liblxqt
     - [ ] updates and links in docs for mlde.w.eggwm
- [ ] create CONTRUBITING section in README's and points to docs/CONTRUBITING file
     - [ ] CONTRUBITING in docs for mlde.d.moonlightde
     - [ ] CONTRUBITING in docs for mlde.l.cppmicroservices
     - [ ] CONTRUBITING in docs for mlde.l.liblxqt
     - [ ] CONTRUBITING in docs for mlde.w.eggwm

**Comment by mckaygerhard** [comment]
fine tune of the work in #40
